-- Tabla para almacenar la "entidad trigonométrica"
CREATE TABLE TRIG_ENTITY (
  ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  HEX_INPUT VARCHAR2(100),
  INT_VALUE NUMBER,
  ANGLE_DEG NUMBER,
  ANGLE_RAD NUMBER,
  SIN_VAL NUMBER,
  COS_VAL NUMBER,
  TAN_VAL NUMBER,
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONFIRMED_BY_WATSON VARCHAR2(100),
  CONFIRMATION_STATUS VARCHAR2(20),
  WATSON_RESPONSE CLOB
);

-- Procedimiento almacenado para confirmar un registro.
CREATE OR REPLACE PROCEDURE SP_CONFIRM_RECORD(
    p_id IN NUMBER,
    p_status IN VARCHAR2,
    p_confirmed_by IN VARCHAR2,
    p_out_message OUT VARCHAR2
) AS
BEGIN
  UPDATE TRIG_ENTITY
    SET CONFIRMATION_STATUS = p_status,
        CONFIRMED_BY_WATSON = p_confirmed_by
    WHERE ID = p_id;
  IF SQL%ROWCOUNT = 0 THEN
    p_out_message := 'NO_RECORD';
  ELSE
    p_out_message := 'OK';
  END IF;
  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    p_out_message := 'ERROR: ' || SQLERRM;
    ROLLBACK;
END SP_CONFIRM_RECORD;
/

SELECT * FROM TRIG_ENTITY;